openapi: 3.0.0
info:
  title: TIPSweb API
  version: 1.0.0

servers:
  - url: https://tips-lrebn2rkuq-uc.a.run.app

paths:
  /auth/info/googlejwt:
    get:
      summary: Get Google JWT Auth Info
      operationId: getGoogleJwtAuthInfo
      security:
        - auth0_jwk: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object

  /auth/info/googleidtoken:
    get:
      summary: Get Google ID Token Auth Info
      operationId: getGoogleIdTokenAuthInfo
      security:
        - auth0_jwk: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object

  /auth/info/firebase:
    get:
      summary: Get Firebase Auth Info
      operationId: getFirebaseAuthInfo
      security:
        - auth0_jwk: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object

components:
  securitySchemes:
    auth0_jwk:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: ""
      x-google-issuer: "${AUTH0_DOMAIN}"
      x-google-jwks_uri: "${JWKS_ENDPOINT}"
      x-google-audiences: "${AUTH0_CLIENT_ID}"